CREATE SEQUENCE SEQ_NOTIFICACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VENTA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLEVENTA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1 NOCACHE;